#!/bin/bash

loginfo() { echo "Info: $*"; }
error() { echo "Error: $*" >&2; exit 1; }

setIfUnset() {
    varname="$1"
    defaultValue="$2"
    eval "if [ \"\$$varname\" = \"\" ]; then $varname=$defaultValue; loginfo \"$varname unset; use \$$varname\"; fi"
}

function indent() {
  c='s/^/       /'
    case $(uname) in
      Darwin) sed -l "$c";;
  *)      sed -u "$c";;
  esac
}

function clearEnvironment() {
  unset GIT_DIR
}

function downloadAndExtract() {
  mkdir -p $1 && curl $2 -o - | tar xzf - -C $1
}

function configureMakeInstall() {
  pushd $1;
  # create build directory
  mkdir -p $2
  cmd="./configure --prefix=$2 && make && make install"
  echo -n "Info: $cmd";
  eval $cmd
  echo "[OK]";
  popd;
}

function mkCompilerDir() {
  local compilerDir=$CACHE_DIR/compilers/$1;
  [[ ! -d "$compilerDir" ]]; mkdir -p $compilerDir;
  echo $compilerDir;
}


